apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: git-next-tag-arm
  name: git-next-tag-arm
spec:
  containers:
#  - image: ghcr.io/joostvdg/git-next-tag:0.4.0-debian
  - image: ghcr.io/joostvdg/git-next-tag:0.5.2-alpine
    name: git-next-tag-arm
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  nodeSelector:
    beta.kubernetes.io/arch: arm64
