apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: git-next-tag-amd
  name: git-next-tag-amd
spec:
  containers:
  - image: ghcr.io/joostvdg/git-next-tag:0.5.2-alpine
    name: git-next-tag-amd
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  nodeSelector:
    beta.kubernetes.io/arch: amd64
